// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package utils

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// NewMockCniDetector creates a new instance of MockCniDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCniDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCniDetector {
	mock := &MockCniDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCniDetector is an autogenerated mock type for the CniDetector type
type MockCniDetector struct {
	mock.Mock
}

type MockCniDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCniDetector) EXPECT() *MockCniDetector_Expecter {
	return &MockCniDetector_Expecter{mock: &_m.Mock}
}

// DetectCNIType provides a mock function for the type MockCniDetector
func (_mock *MockCniDetector) DetectCNIType(ctx context.Context) (CNIType, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DetectCNIType")
	}

	var r0 CNIType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (CNIType, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) CNIType); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(CNIType)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCniDetector_DetectCNIType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectCNIType'
type MockCniDetector_DetectCNIType_Call struct {
	*mock.Call
}

// DetectCNIType is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCniDetector_Expecter) DetectCNIType(ctx interface{}) *MockCniDetector_DetectCNIType_Call {
	return &MockCniDetector_DetectCNIType_Call{Call: _e.mock.On("DetectCNIType", ctx)}
}

func (_c *MockCniDetector_DetectCNIType_Call) Run(run func(ctx context.Context)) *MockCniDetector_DetectCNIType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCniDetector_DetectCNIType_Call) Return(cNIType CNIType, err error) *MockCniDetector_DetectCNIType_Call {
	_c.Call.Return(cNIType, err)
	return _c
}

func (_c *MockCniDetector_DetectCNIType_Call) RunAndReturn(run func(ctx context.Context) (CNIType, error)) *MockCniDetector_DetectCNIType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEndpointResolver creates a new instance of MockEndpointResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEndpointResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEndpointResolver {
	mock := &MockEndpointResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEndpointResolver is an autogenerated mock type for the EndpointResolver type
type MockEndpointResolver struct {
	mock.Mock
}

type MockEndpointResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEndpointResolver) EXPECT() *MockEndpointResolver_Expecter {
	return &MockEndpointResolver_Expecter{mock: &_m.Mock}
}

// GetListTargetPort provides a mock function for the type MockEndpointResolver
func (_mock *MockEndpointResolver) GetListTargetPort(ctx context.Context, svcKey types.NamespacedName, port intstr.IntOrString) ([]int, error) {
	ret := _mock.Called(ctx, svcKey, port)

	if len(ret) == 0 {
		panic("no return value specified for GetListTargetPort")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NamespacedName, intstr.IntOrString) ([]int, error)); ok {
		return returnFunc(ctx, svcKey, port)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NamespacedName, intstr.IntOrString) []int); ok {
		r0 = returnFunc(ctx, svcKey, port)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.NamespacedName, intstr.IntOrString) error); ok {
		r1 = returnFunc(ctx, svcKey, port)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEndpointResolver_GetListTargetPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListTargetPort'
type MockEndpointResolver_GetListTargetPort_Call struct {
	*mock.Call
}

// GetListTargetPort is a helper method to define mock.On call
//   - ctx context.Context
//   - svcKey types.NamespacedName
//   - port intstr.IntOrString
func (_e *MockEndpointResolver_Expecter) GetListTargetPort(ctx interface{}, svcKey interface{}, port interface{}) *MockEndpointResolver_GetListTargetPort_Call {
	return &MockEndpointResolver_GetListTargetPort_Call{Call: _e.mock.On("GetListTargetPort", ctx, svcKey, port)}
}

func (_c *MockEndpointResolver_GetListTargetPort_Call) Run(run func(ctx context.Context, svcKey types.NamespacedName, port intstr.IntOrString)) *MockEndpointResolver_GetListTargetPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.NamespacedName
		if args[1] != nil {
			arg1 = args[1].(types.NamespacedName)
		}
		var arg2 intstr.IntOrString
		if args[2] != nil {
			arg2 = args[2].(intstr.IntOrString)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEndpointResolver_GetListTargetPort_Call) Return(ints []int, err error) *MockEndpointResolver_GetListTargetPort_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockEndpointResolver_GetListTargetPort_Call) RunAndReturn(run func(ctx context.Context, svcKey types.NamespacedName, port intstr.IntOrString) ([]int, error)) *MockEndpointResolver_GetListTargetPort_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveNodePortEndpoints provides a mock function for the type MockEndpointResolver
func (_mock *MockEndpointResolver) ResolveNodePortEndpoints(ctx context.Context, svcKey types.NamespacedName, port intstr.IntOrString, opts ...EndpointResolveOption) ([]EndpointAddress, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, svcKey, port, opts)
	} else {
		tmpRet = _mock.Called(ctx, svcKey, port)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ResolveNodePortEndpoints")
	}

	var r0 []EndpointAddress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NamespacedName, intstr.IntOrString, ...EndpointResolveOption) ([]EndpointAddress, error)); ok {
		return returnFunc(ctx, svcKey, port, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NamespacedName, intstr.IntOrString, ...EndpointResolveOption) []EndpointAddress); ok {
		r0 = returnFunc(ctx, svcKey, port, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]EndpointAddress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.NamespacedName, intstr.IntOrString, ...EndpointResolveOption) error); ok {
		r1 = returnFunc(ctx, svcKey, port, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEndpointResolver_ResolveNodePortEndpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveNodePortEndpoints'
type MockEndpointResolver_ResolveNodePortEndpoints_Call struct {
	*mock.Call
}

// ResolveNodePortEndpoints is a helper method to define mock.On call
//   - ctx context.Context
//   - svcKey types.NamespacedName
//   - port intstr.IntOrString
//   - opts ...EndpointResolveOption
func (_e *MockEndpointResolver_Expecter) ResolveNodePortEndpoints(ctx interface{}, svcKey interface{}, port interface{}, opts ...interface{}) *MockEndpointResolver_ResolveNodePortEndpoints_Call {
	return &MockEndpointResolver_ResolveNodePortEndpoints_Call{Call: _e.mock.On("ResolveNodePortEndpoints",
		append([]interface{}{ctx, svcKey, port}, opts...)...)}
}

func (_c *MockEndpointResolver_ResolveNodePortEndpoints_Call) Run(run func(ctx context.Context, svcKey types.NamespacedName, port intstr.IntOrString, opts ...EndpointResolveOption)) *MockEndpointResolver_ResolveNodePortEndpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.NamespacedName
		if args[1] != nil {
			arg1 = args[1].(types.NamespacedName)
		}
		var arg2 intstr.IntOrString
		if args[2] != nil {
			arg2 = args[2].(intstr.IntOrString)
		}
		var arg3 []EndpointResolveOption
		var variadicArgs []EndpointResolveOption
		if len(args) > 3 {
			variadicArgs = args[3].([]EndpointResolveOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockEndpointResolver_ResolveNodePortEndpoints_Call) Return(endpointAddresss []EndpointAddress, err error) *MockEndpointResolver_ResolveNodePortEndpoints_Call {
	_c.Call.Return(endpointAddresss, err)
	return _c
}

func (_c *MockEndpointResolver_ResolveNodePortEndpoints_Call) RunAndReturn(run func(ctx context.Context, svcKey types.NamespacedName, port intstr.IntOrString, opts ...EndpointResolveOption) ([]EndpointAddress, error)) *MockEndpointResolver_ResolveNodePortEndpoints_Call {
	_c.Call.Return(run)
	return _c
}

// ResolvePodEndpoints provides a mock function for the type MockEndpointResolver
func (_mock *MockEndpointResolver) ResolvePodEndpoints(ctx context.Context, svcKey types.NamespacedName, port intstr.IntOrString, opts ...EndpointResolveOption) ([]EndpointAddress, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, svcKey, port, opts)
	} else {
		tmpRet = _mock.Called(ctx, svcKey, port)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ResolvePodEndpoints")
	}

	var r0 []EndpointAddress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NamespacedName, intstr.IntOrString, ...EndpointResolveOption) ([]EndpointAddress, error)); ok {
		return returnFunc(ctx, svcKey, port, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NamespacedName, intstr.IntOrString, ...EndpointResolveOption) []EndpointAddress); ok {
		r0 = returnFunc(ctx, svcKey, port, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]EndpointAddress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.NamespacedName, intstr.IntOrString, ...EndpointResolveOption) error); ok {
		r1 = returnFunc(ctx, svcKey, port, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEndpointResolver_ResolvePodEndpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePodEndpoints'
type MockEndpointResolver_ResolvePodEndpoints_Call struct {
	*mock.Call
}

// ResolvePodEndpoints is a helper method to define mock.On call
//   - ctx context.Context
//   - svcKey types.NamespacedName
//   - port intstr.IntOrString
//   - opts ...EndpointResolveOption
func (_e *MockEndpointResolver_Expecter) ResolvePodEndpoints(ctx interface{}, svcKey interface{}, port interface{}, opts ...interface{}) *MockEndpointResolver_ResolvePodEndpoints_Call {
	return &MockEndpointResolver_ResolvePodEndpoints_Call{Call: _e.mock.On("ResolvePodEndpoints",
		append([]interface{}{ctx, svcKey, port}, opts...)...)}
}

func (_c *MockEndpointResolver_ResolvePodEndpoints_Call) Run(run func(ctx context.Context, svcKey types.NamespacedName, port intstr.IntOrString, opts ...EndpointResolveOption)) *MockEndpointResolver_ResolvePodEndpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.NamespacedName
		if args[1] != nil {
			arg1 = args[1].(types.NamespacedName)
		}
		var arg2 intstr.IntOrString
		if args[2] != nil {
			arg2 = args[2].(intstr.IntOrString)
		}
		var arg3 []EndpointResolveOption
		var variadicArgs []EndpointResolveOption
		if len(args) > 3 {
			variadicArgs = args[3].([]EndpointResolveOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockEndpointResolver_ResolvePodEndpoints_Call) Return(endpointAddresss []EndpointAddress, err error) *MockEndpointResolver_ResolvePodEndpoints_Call {
	_c.Call.Return(endpointAddresss, err)
	return _c
}

func (_c *MockEndpointResolver_ResolvePodEndpoints_Call) RunAndReturn(run func(ctx context.Context, svcKey types.NamespacedName, port intstr.IntOrString, opts ...EndpointResolveOption) ([]EndpointAddress, error)) *MockEndpointResolver_ResolvePodEndpoints_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNameHelper creates a new instance of MockNameHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNameHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNameHelper {
	mock := &MockNameHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNameHelper is an autogenerated mock type for the NameHelper type
type MockNameHelper struct {
	mock.Mock
}

type MockNameHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNameHelper) EXPECT() *MockNameHelper_Expecter {
	return &MockNameHelper_Expecter{mock: &_m.Mock}
}

// GenL4ListenerName provides a mock function for the type MockNameHelper
func (_mock *MockNameHelper) GenL4ListenerName(pPort v1.ServicePort) string {
	ret := _mock.Called(pPort)

	if len(ret) == 0 {
		panic("no return value specified for GenL4ListenerName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(v1.ServicePort) string); ok {
		r0 = returnFunc(pPort)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNameHelper_GenL4ListenerName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenL4ListenerName'
type MockNameHelper_GenL4ListenerName_Call struct {
	*mock.Call
}

// GenL4ListenerName is a helper method to define mock.On call
//   - pPort v1.ServicePort
func (_e *MockNameHelper_Expecter) GenL4ListenerName(pPort interface{}) *MockNameHelper_GenL4ListenerName_Call {
	return &MockNameHelper_GenL4ListenerName_Call{Call: _e.mock.On("GenL4ListenerName", pPort)}
}

func (_c *MockNameHelper_GenL4ListenerName_Call) Run(run func(pPort v1.ServicePort)) *MockNameHelper_GenL4ListenerName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1.ServicePort
		if args[0] != nil {
			arg0 = args[0].(v1.ServicePort)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNameHelper_GenL4ListenerName_Call) Return(s string) *MockNameHelper_GenL4ListenerName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNameHelper_GenL4ListenerName_Call) RunAndReturn(run func(pPort v1.ServicePort) string) *MockNameHelper_GenL4ListenerName_Call {
	_c.Call.Return(run)
	return _c
}

// GenL4PoolName provides a mock function for the type MockNameHelper
func (_mock *MockNameHelper) GenL4PoolName(pPort v1.ServicePort, realProtocol string) string {
	ret := _mock.Called(pPort, realProtocol)

	if len(ret) == 0 {
		panic("no return value specified for GenL4PoolName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(v1.ServicePort, string) string); ok {
		r0 = returnFunc(pPort, realProtocol)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNameHelper_GenL4PoolName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenL4PoolName'
type MockNameHelper_GenL4PoolName_Call struct {
	*mock.Call
}

// GenL4PoolName is a helper method to define mock.On call
//   - pPort v1.ServicePort
//   - realProtocol string
func (_e *MockNameHelper_Expecter) GenL4PoolName(pPort interface{}, realProtocol interface{}) *MockNameHelper_GenL4PoolName_Call {
	return &MockNameHelper_GenL4PoolName_Call{Call: _e.mock.On("GenL4PoolName", pPort, realProtocol)}
}

func (_c *MockNameHelper_GenL4PoolName_Call) Run(run func(pPort v1.ServicePort, realProtocol string)) *MockNameHelper_GenL4PoolName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1.ServicePort
		if args[0] != nil {
			arg0 = args[0].(v1.ServicePort)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNameHelper_GenL4PoolName_Call) Return(s string) *MockNameHelper_GenL4PoolName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNameHelper_GenL4PoolName_Call) RunAndReturn(run func(pPort v1.ServicePort, realProtocol string) string) *MockNameHelper_GenL4PoolName_Call {
	_c.Call.Return(run)
	return _c
}

// GenL7PolicyName provides a mock function for the type MockNameHelper
func (_mock *MockNameHelper) GenL7PolicyName(mode bool, ruleIndex int, pathIndex int) string {
	ret := _mock.Called(mode, ruleIndex, pathIndex)

	if len(ret) == 0 {
		panic("no return value specified for GenL7PolicyName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(bool, int, int) string); ok {
		r0 = returnFunc(mode, ruleIndex, pathIndex)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNameHelper_GenL7PolicyName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenL7PolicyName'
type MockNameHelper_GenL7PolicyName_Call struct {
	*mock.Call
}

// GenL7PolicyName is a helper method to define mock.On call
//   - mode bool
//   - ruleIndex int
//   - pathIndex int
func (_e *MockNameHelper_Expecter) GenL7PolicyName(mode interface{}, ruleIndex interface{}, pathIndex interface{}) *MockNameHelper_GenL7PolicyName_Call {
	return &MockNameHelper_GenL7PolicyName_Call{Call: _e.mock.On("GenL7PolicyName", mode, ruleIndex, pathIndex)}
}

func (_c *MockNameHelper_GenL7PolicyName_Call) Run(run func(mode bool, ruleIndex int, pathIndex int)) *MockNameHelper_GenL7PolicyName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNameHelper_GenL7PolicyName_Call) Return(s string) *MockNameHelper_GenL7PolicyName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNameHelper_GenL7PolicyName_Call) RunAndReturn(run func(mode bool, ruleIndex int, pathIndex int) string) *MockNameHelper_GenL7PolicyName_Call {
	_c.Call.Return(run)
	return _c
}

// GenL7PoolName provides a mock function for the type MockNameHelper
func (_mock *MockNameHelper) GenL7PoolName(serviceName string, port int) string {
	ret := _mock.Called(serviceName, port)

	if len(ret) == 0 {
		panic("no return value specified for GenL7PoolName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, int) string); ok {
		r0 = returnFunc(serviceName, port)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNameHelper_GenL7PoolName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenL7PoolName'
type MockNameHelper_GenL7PoolName_Call struct {
	*mock.Call
}

// GenL7PoolName is a helper method to define mock.On call
//   - serviceName string
//   - port int
func (_e *MockNameHelper_Expecter) GenL7PoolName(serviceName interface{}, port interface{}) *MockNameHelper_GenL7PoolName_Call {
	return &MockNameHelper_GenL7PoolName_Call{Call: _e.mock.On("GenL7PoolName", serviceName, port)}
}

func (_c *MockNameHelper_GenL7PoolName_Call) Run(run func(serviceName string, port int)) *MockNameHelper_GenL7PoolName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNameHelper_GenL7PoolName_Call) Return(s string) *MockNameHelper_GenL7PoolName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNameHelper_GenL7PoolName_Call) RunAndReturn(run func(serviceName string, port int) string) *MockNameHelper_GenL7PoolName_Call {
	_c.Call.Return(run)
	return _c
}

// GenL7ListenerName provides a mock function for the type MockNameHelper
func (_mock *MockNameHelper) GenL7ListenerName(listenerName string) string {
	ret := _mock.Called(listenerName)

	if len(ret) == 0 {
		panic("no return value specified for GenL7ListenerName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(listenerName)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNameHelper_GenL7ListenerName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenL7ListenerName'
type MockNameHelper_GenL7ListenerName_Call struct {
	*mock.Call
}

// GenL7ListenerName is a helper method to define mock.On call
//   - listenerName string
func (_e *MockNameHelper_Expecter) GenL7ListenerName(listenerName interface{}) *MockNameHelper_GenL7ListenerName_Call {
	return &MockNameHelper_GenL7ListenerName_Call{Call: _e.mock.On("GenL7ListenerName", listenerName)}
}

func (_c *MockNameHelper_GenL7ListenerName_Call) Run(run func(listenerName string)) *MockNameHelper_GenL7ListenerName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockNameHelper_GenL7ListenerName_Call) Return(s string) *MockNameHelper_GenL7ListenerName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNameHelper_GenL7ListenerName_Call) RunAndReturn(run func(listenerName string) string) *MockNameHelper_GenL7ListenerName_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateHash provides a mock function for the type MockNameHelper
func (_mock *MockNameHelper) GenerateHash() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateHash")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNameHelper_GenerateHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateHash'
type MockNameHelper_GenerateHash_Call struct {
	*mock.Call
}

// GenerateHash is a helper method to define mock.On call
func (_e *MockNameHelper_Expecter) GenerateHash() *MockNameHelper_GenerateHash_Call {
	return &MockNameHelper_GenerateHash_Call{Call: _e.mock.On("GenerateHash")}
}

func (_c *MockNameHelper_GenerateHash_Call) Run(run func()) *MockNameHelper_GenerateHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNameHelper_GenerateHash_Call) Return(s string) *MockNameHelper_GenerateHash_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNameHelper_GenerateHash_Call) RunAndReturn(run func() string) *MockNameHelper_GenerateHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoadBalancerDefaultName provides a mock function for the type MockNameHelper
func (_mock *MockNameHelper) GetLoadBalancerDefaultName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLoadBalancerDefaultName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNameHelper_GetLoadBalancerDefaultName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoadBalancerDefaultName'
type MockNameHelper_GetLoadBalancerDefaultName_Call struct {
	*mock.Call
}

// GetLoadBalancerDefaultName is a helper method to define mock.On call
func (_e *MockNameHelper_Expecter) GetLoadBalancerDefaultName() *MockNameHelper_GetLoadBalancerDefaultName_Call {
	return &MockNameHelper_GetLoadBalancerDefaultName_Call{Call: _e.mock.On("GetLoadBalancerDefaultName")}
}

func (_c *MockNameHelper_GetLoadBalancerDefaultName_Call) Run(run func()) *MockNameHelper_GetLoadBalancerDefaultName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNameHelper_GetLoadBalancerDefaultName_Call) Return(s string) *MockNameHelper_GetLoadBalancerDefaultName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNameHelper_GetLoadBalancerDefaultName_Call) RunAndReturn(run func() string) *MockNameHelper_GetLoadBalancerDefaultName_Call {
	_c.Call.Return(run)
	return _c
}
