resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: vcr.vngcloud.vn/81-vks-public/vngcloud-load-balancer-controller
  newTag: v0.3.24
