# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     control-plane: manager
#     app.kubernetes.io/name: vngcloud-load-balancer-controller
#     app.kubernetes.io/managed-by: kustomize
#   name: system
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: system
type: Opaque
stringData:
  config.yaml: |
    chartVersion: 0.0.1
    cluster:
      clusterID: ""
      clusterName: ""
    global:
      clientID: ____________________________________
      clientSecret: ____________________________________
      identityURL: https://iamapis.vngcloud.vn/accounts-api
      vserverURL: https://hcm-3.api.vngcloud.vn/vserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: manager
    app.kubernetes.io/name: vngcloud-load-balancer-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: manager
    spec:
      nodeSelector: {}
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: components.vks.vngcloud.vn/vks-managed-components
          operator: Exists
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: arm64
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  control-plane: manager
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. Openshift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: vcr.vngcloud.vn/81-vks-public/vngcloud-load-balancer-controller:v0.3.22
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: secret
          mountPath: /etc/vngcloud-load-balancer-controller
          readOnly: true
        - mountPath: /etc/hosts
          name: add-hosts
          readOnly: true
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
      volumes:
      - secret:
          secretName: vngcloud-load-balancer-controller-mysecret
        name: secret
      - hostPath:
          path: /etc/hosts
          type: ""
        name: add-hosts
