# This rule is not used by the project vngcloud-load-balancer-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the vks.vngcloud.vn.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vngcloud-load-balancer-controller
    app.kubernetes.io/managed-by: kustomize
  name: lbc-editor-role
rules:
- apiGroups:
  - vks.vngcloud.vn
  resources:
  - loadbalancerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vks.vngcloud.vn
  resources:
  - loadbalancerconfigs/status
  verbs:
  - get
