# This rule is not used by the project vngcloud-load-balancer-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vks.vngcloud.vn resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vngcloud-load-balancer-controller
    app.kubernetes.io/managed-by: kustomize
  name: vlbc-viewer-role
rules:
- apiGroups:
  - vks.vngcloud.vn
  resources:
  - vngcloudloadbalancerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vks.vngcloud.vn
  resources:
  - vngcloudloadbalancerconfigs/status
  verbs:
  - get
