apiVersion: vks.vngcloud.vn/v1alpha1
kind: GlobalLoadBalancerConfig
metadata:
  labels:
    app.kubernetes.io/name: vngcloud-load-balancer-controller
    app.kubernetes.io/managed-by: kustomize
  name: globalloadbalancerconfig-sample
spec:
  # TODO(user): Add fields here
