//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/vngcloud/vngcloud-go-sdk/v2/vngcloud/services/loadbalancer/v2"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreatedListener) DeepCopyInto(out *CreatedListener) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreatedListener.
func (in *CreatedListener) DeepCopy() *CreatedListener {
	if in == nil {
		return nil
	}
	out := new(CreatedListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreatedPool) DeepCopyInto(out *CreatedPool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreatedPool.
func (in *CreatedPool) DeepCopy() *CreatedPool {
	if in == nil {
		return nil
	}
	out := new(CreatedPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Listener) DeepCopyInto(out *Listener) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DefaultPoolName != nil {
		in, out := &in.DefaultPoolName, &out.DefaultPoolName
		*out = new(string)
		**out = **in
	}
	if in.TimeoutClient != nil {
		in, out := &in.TimeoutClient, &out.TimeoutClient
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutMember != nil {
		in, out := &in.TimeoutMember, &out.TimeoutMember
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutConnection != nil {
		in, out := &in.TimeoutConnection, &out.TimeoutConnection
		*out = new(int32)
		**out = **in
	}
	if in.AllowedCidrs != nil {
		in, out := &in.AllowedCidrs, &out.AllowedCidrs
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Listener.
func (in *Listener) DeepCopy() *Listener {
	if in == nil {
		return nil
	}
	out := new(Listener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfig) DeepCopyInto(out *LoadBalancerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfig.
func (in *LoadBalancerConfig) DeepCopy() *LoadBalancerConfig {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfigList) DeepCopyInto(out *LoadBalancerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfigList.
func (in *LoadBalancerConfigList) DeepCopy() *LoadBalancerConfigList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfigSpec) DeepCopyInto(out *LoadBalancerConfigSpec) {
	*out = *in
	if in.ClusterId != nil {
		in, out := &in.ClusterId, &out.ClusterId
		*out = new(string)
		**out = **in
	}
	if in.BackendSubnetId != nil {
		in, out := &in.BackendSubnetId, &out.BackendSubnetId
		*out = new(string)
		**out = **in
	}
	if in.PackageId != nil {
		in, out := &in.PackageId, &out.PackageId
		*out = new(string)
		**out = **in
	}
	if in.Scheme != nil {
		in, out := &in.Scheme, &out.Scheme
		*out = new(v2.LoadBalancerScheme)
		**out = **in
	}
	if in.LoadBalancerId != nil {
		in, out := &in.LoadBalancerId, &out.LoadBalancerId
		*out = new(string)
		**out = **in
	}
	if in.EnableAutoscale != nil {
		in, out := &in.EnableAutoscale, &out.EnableAutoscale
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IsPoc != nil {
		in, out := &in.IsPoc, &out.IsPoc
		*out = new(bool)
		**out = **in
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]Listener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]Pool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfigSpec.
func (in *LoadBalancerConfigSpec) DeepCopy() *LoadBalancerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfigStatus) DeepCopyInto(out *LoadBalancerConfigStatus) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerId != nil {
		in, out := &in.LoadBalancerId, &out.LoadBalancerId
		*out = new(string)
		**out = **in
	}
	if in.CreatedTags != nil {
		in, out := &in.CreatedTags, &out.CreatedTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CreatedPools != nil {
		in, out := &in.CreatedPools, &out.CreatedPools
		*out = make([]CreatedPool, len(*in))
		copy(*out, *in)
	}
	if in.CreatedListeners != nil {
		in, out := &in.CreatedListeners, &out.CreatedListeners
		*out = make([]CreatedListener, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfigStatus.
func (in *LoadBalancerConfigStatus) DeepCopy() *LoadBalancerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedSecurityGroup) DeepCopyInto(out *ManagedSecurityGroup) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]NodeSecurityGroupRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedSecurityGroup.
func (in *ManagedSecurityGroup) DeepCopy() *ManagedSecurityGroup {
	if in == nil {
		return nil
	}
	out := new(ManagedSecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedSecurityGroupStatus) DeepCopyInto(out *ManagedSecurityGroupStatus) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedSecurityGroupStatus.
func (in *ManagedSecurityGroupStatus) DeepCopy() *ManagedSecurityGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedSecurityGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInfo) DeepCopyInto(out *NodeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInfo.
func (in *NodeInfo) DeepCopy() *NodeInfo {
	if in == nil {
		return nil
	}
	out := new(NodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSecurityGroup) DeepCopyInto(out *NodeSecurityGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSecurityGroup.
func (in *NodeSecurityGroup) DeepCopy() *NodeSecurityGroup {
	if in == nil {
		return nil
	}
	out := new(NodeSecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSecurityGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSecurityGroupList) DeepCopyInto(out *NodeSecurityGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSecurityGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSecurityGroupList.
func (in *NodeSecurityGroupList) DeepCopy() *NodeSecurityGroupList {
	if in == nil {
		return nil
	}
	out := new(NodeSecurityGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSecurityGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSecurityGroupRule) DeepCopyInto(out *NodeSecurityGroupRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSecurityGroupRule.
func (in *NodeSecurityGroupRule) DeepCopy() *NodeSecurityGroupRule {
	if in == nil {
		return nil
	}
	out := new(NodeSecurityGroupRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSecurityGroupSpec) DeepCopyInto(out *NodeSecurityGroupSpec) {
	*out = *in
	if in.SelectNodeLabels != nil {
		in, out := &in.SelectNodeLabels, &out.SelectNodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AttachSecurityGroups != nil {
		in, out := &in.AttachSecurityGroups, &out.AttachSecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedSecurityGroup != nil {
		in, out := &in.ManagedSecurityGroup, &out.ManagedSecurityGroup
		*out = new(ManagedSecurityGroup)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSecurityGroupSpec.
func (in *NodeSecurityGroupSpec) DeepCopy() *NodeSecurityGroupSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSecurityGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSecurityGroupStatus) DeepCopyInto(out *NodeSecurityGroupStatus) {
	*out = *in
	if in.SelectedNodes != nil {
		in, out := &in.SelectedNodes, &out.SelectedNodes
		*out = make([]NodeInfo, len(*in))
		copy(*out, *in)
	}
	in.ManagedSecurityGroup.DeepCopyInto(&out.ManagedSecurityGroup)
	if in.ServerSecurityGroups != nil {
		in, out := &in.ServerSecurityGroups, &out.ServerSecurityGroups
		*out = make([]ServerSecurityGroupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSecurityGroupStatus.
func (in *NodeSecurityGroupStatus) DeepCopy() *NodeSecurityGroupStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSecurityGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pool) DeepCopyInto(out *Pool) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Algorithm != nil {
		in, out := &in.Algorithm, &out.Algorithm
		*out = new(v2.PoolAlgorithm)
		**out = **in
	}
	in.HealthMonitor.DeepCopyInto(&out.HealthMonitor)
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]PoolMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pool.
func (in *Pool) DeepCopy() *Pool {
	if in == nil {
		return nil
	}
	out := new(Pool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolHealthMonitor) DeepCopyInto(out *PoolHealthMonitor) {
	*out = *in
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(int)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(int)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(int)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolHealthMonitor.
func (in *PoolHealthMonitor) DeepCopy() *PoolHealthMonitor {
	if in == nil {
		return nil
	}
	out := new(PoolHealthMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolMember) DeepCopyInto(out *PoolMember) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int)
		**out = **in
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolMember.
func (in *PoolMember) DeepCopy() *PoolMember {
	if in == nil {
		return nil
	}
	out := new(PoolMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSecurityGroupStatus) DeepCopyInto(out *ServerSecurityGroupStatus) {
	*out = *in
	if in.AttachedSecurityGroupIds != nil {
		in, out := &in.AttachedSecurityGroupIds, &out.AttachedSecurityGroupIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSecurityGroupStatus.
func (in *ServerSecurityGroupStatus) DeepCopy() *ServerSecurityGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ServerSecurityGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudGlobalLoadBalancer) DeepCopyInto(out *VngcloudGlobalLoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudGlobalLoadBalancer.
func (in *VngcloudGlobalLoadBalancer) DeepCopy() *VngcloudGlobalLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(VngcloudGlobalLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VngcloudGlobalLoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudGlobalLoadBalancerList) DeepCopyInto(out *VngcloudGlobalLoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VngcloudGlobalLoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudGlobalLoadBalancerList.
func (in *VngcloudGlobalLoadBalancerList) DeepCopy() *VngcloudGlobalLoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(VngcloudGlobalLoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VngcloudGlobalLoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudGlobalLoadBalancerSpec) DeepCopyInto(out *VngcloudGlobalLoadBalancerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudGlobalLoadBalancerSpec.
func (in *VngcloudGlobalLoadBalancerSpec) DeepCopy() *VngcloudGlobalLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(VngcloudGlobalLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudGlobalLoadBalancerStatus) DeepCopyInto(out *VngcloudGlobalLoadBalancerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudGlobalLoadBalancerStatus.
func (in *VngcloudGlobalLoadBalancerStatus) DeepCopy() *VngcloudGlobalLoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(VngcloudGlobalLoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}
