//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/vngcloud/vngcloud-go-sdk/v2/vngcloud/services/loadbalancer/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationLoadBalancerConfig) DeepCopyInto(out *ApplicationLoadBalancerConfig) {
	*out = *in
	if in.EnableStickySession != nil {
		in, out := &in.EnableStickySession, &out.EnableStickySession
		*out = new(bool)
		**out = **in
	}
	if in.EnableTLSEncryption != nil {
		in, out := &in.EnableTLSEncryption, &out.EnableTLSEncryption
		*out = new(bool)
		**out = **in
	}
	if in.CertificateIDs != nil {
		in, out := &in.CertificateIDs, &out.CertificateIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientCertificateID != nil {
		in, out := &in.ClientCertificateID, &out.ClientCertificateID
		*out = new(string)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InsertHeaders != nil {
		in, out := &in.InsertHeaders, &out.InsertHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImplementationSpecificParams != nil {
		in, out := &in.ImplementationSpecificParams, &out.ImplementationSpecificParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AutoReorderPolicies != nil {
		in, out := &in.AutoReorderPolicies, &out.AutoReorderPolicies
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationLoadBalancerConfig.
func (in *ApplicationLoadBalancerConfig) DeepCopy() *ApplicationLoadBalancerConfig {
	if in == nil {
		return nil
	}
	out := new(ApplicationLoadBalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsertHeader) DeepCopyInto(out *InsertHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsertHeader.
func (in *InsertHeader) DeepCopy() *InsertHeader {
	if in == nil {
		return nil
	}
	out := new(InsertHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L7Rule) DeepCopyInto(out *L7Rule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L7Rule.
func (in *L7Rule) DeepCopy() *L7Rule {
	if in == nil {
		return nil
	}
	out := new(L7Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Listener) DeepCopyInto(out *Listener) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DefaultPoolName != nil {
		in, out := &in.DefaultPoolName, &out.DefaultPoolName
		*out = new(string)
		**out = **in
	}
	if in.TimeoutClient != nil {
		in, out := &in.TimeoutClient, &out.TimeoutClient
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutMember != nil {
		in, out := &in.TimeoutMember, &out.TimeoutMember
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutConnection != nil {
		in, out := &in.TimeoutConnection, &out.TimeoutConnection
		*out = new(int32)
		**out = **in
	}
	if in.AllowedCidrs != nil {
		in, out := &in.AllowedCidrs, &out.AllowedCidrs
		*out = new(string)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InsertHeaders != nil {
		in, out := &in.InsertHeaders, &out.InsertHeaders
		*out = make([]InsertHeader, len(*in))
		copy(*out, *in)
	}
	if in.CertificateAuthorities != nil {
		in, out := &in.CertificateAuthorities, &out.CertificateAuthorities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultCertificateAuthority != nil {
		in, out := &in.DefaultCertificateAuthority, &out.DefaultCertificateAuthority
		*out = new(string)
		**out = **in
	}
	if in.ClientCertificateAuthentication != nil {
		in, out := &in.ClientCertificateAuthentication, &out.ClientCertificateAuthentication
		*out = new(string)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]Policy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Listener.
func (in *Listener) DeepCopy() *Listener {
	if in == nil {
		return nil
	}
	out := new(Listener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkLoadBalancerConfig) DeepCopyInto(out *NetworkLoadBalancerConfig) {
	*out = *in
	if in.EnableProxyProtocol != nil {
		in, out := &in.EnableProxyProtocol, &out.EnableProxyProtocol
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkLoadBalancerConfig.
func (in *NetworkLoadBalancerConfig) DeepCopy() *NetworkLoadBalancerConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkLoadBalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.RedirectPoolName != nil {
		in, out := &in.RedirectPoolName, &out.RedirectPoolName
		*out = new(string)
		**out = **in
	}
	if in.RedirectUrl != nil {
		in, out := &in.RedirectUrl, &out.RedirectUrl
		*out = new(string)
		**out = **in
	}
	if in.RedirectHttpCode != nil {
		in, out := &in.RedirectHttpCode, &out.RedirectHttpCode
		*out = new(int32)
		**out = **in
	}
	if in.KeepQueryString != nil {
		in, out := &in.KeepQueryString, &out.KeepQueryString
		*out = new(bool)
		**out = **in
	}
	if in.L7Rules != nil {
		in, out := &in.L7Rules, &out.L7Rules
		*out = make([]L7Rule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pool) DeepCopyInto(out *Pool) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Algorithm != nil {
		in, out := &in.Algorithm, &out.Algorithm
		*out = new(v2.PoolAlgorithm)
		**out = **in
	}
	if in.Stickiness != nil {
		in, out := &in.Stickiness, &out.Stickiness
		*out = new(bool)
		**out = **in
	}
	if in.TLSEncryption != nil {
		in, out := &in.TLSEncryption, &out.TLSEncryption
		*out = new(bool)
		**out = **in
	}
	in.HealthMonitor.DeepCopyInto(&out.HealthMonitor)
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]PoolMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pool.
func (in *Pool) DeepCopy() *Pool {
	if in == nil {
		return nil
	}
	out := new(Pool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolHealthMonitor) DeepCopyInto(out *PoolHealthMonitor) {
	*out = *in
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(int)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(int)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(int)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
	if in.HealthCheckMethod != nil {
		in, out := &in.HealthCheckMethod, &out.HealthCheckMethod
		*out = new(v2.HealthCheckMethod)
		**out = **in
	}
	if in.HttpVersion != nil {
		in, out := &in.HttpVersion, &out.HttpVersion
		*out = new(v2.HealthCheckHttpVersion)
		**out = **in
	}
	if in.HealthCheckPath != nil {
		in, out := &in.HealthCheckPath, &out.HealthCheckPath
		*out = new(string)
		**out = **in
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.SuccessCode != nil {
		in, out := &in.SuccessCode, &out.SuccessCode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolHealthMonitor.
func (in *PoolHealthMonitor) DeepCopy() *PoolHealthMonitor {
	if in == nil {
		return nil
	}
	out := new(PoolHealthMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolMember) DeepCopyInto(out *PoolMember) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int)
		**out = **in
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolMember.
func (in *PoolMember) DeepCopy() *PoolMember {
	if in == nil {
		return nil
	}
	out := new(PoolMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupRule) DeepCopyInto(out *SecurityGroupRule) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupRule.
func (in *SecurityGroupRule) DeepCopy() *SecurityGroupRule {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudGlobalLoadBalancer) DeepCopyInto(out *VngcloudGlobalLoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudGlobalLoadBalancer.
func (in *VngcloudGlobalLoadBalancer) DeepCopy() *VngcloudGlobalLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(VngcloudGlobalLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VngcloudGlobalLoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudGlobalLoadBalancerList) DeepCopyInto(out *VngcloudGlobalLoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VngcloudGlobalLoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudGlobalLoadBalancerList.
func (in *VngcloudGlobalLoadBalancerList) DeepCopy() *VngcloudGlobalLoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(VngcloudGlobalLoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VngcloudGlobalLoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudGlobalLoadBalancerSpec) DeepCopyInto(out *VngcloudGlobalLoadBalancerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudGlobalLoadBalancerSpec.
func (in *VngcloudGlobalLoadBalancerSpec) DeepCopy() *VngcloudGlobalLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(VngcloudGlobalLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudGlobalLoadBalancerStatus) DeepCopyInto(out *VngcloudGlobalLoadBalancerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudGlobalLoadBalancerStatus.
func (in *VngcloudGlobalLoadBalancerStatus) DeepCopy() *VngcloudGlobalLoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(VngcloudGlobalLoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudLoadBalancerConfig) DeepCopyInto(out *VngcloudLoadBalancerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudLoadBalancerConfig.
func (in *VngcloudLoadBalancerConfig) DeepCopy() *VngcloudLoadBalancerConfig {
	if in == nil {
		return nil
	}
	out := new(VngcloudLoadBalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VngcloudLoadBalancerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudLoadBalancerConfigList) DeepCopyInto(out *VngcloudLoadBalancerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VngcloudLoadBalancerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudLoadBalancerConfigList.
func (in *VngcloudLoadBalancerConfigList) DeepCopy() *VngcloudLoadBalancerConfigList {
	if in == nil {
		return nil
	}
	out := new(VngcloudLoadBalancerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VngcloudLoadBalancerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudLoadBalancerConfigSpec) DeepCopyInto(out *VngcloudLoadBalancerConfigSpec) {
	*out = *in
	if in.PackageID != nil {
		in, out := &in.PackageID, &out.PackageID
		*out = new(string)
		**out = **in
	}
	if in.Scheme != nil {
		in, out := &in.Scheme, &out.Scheme
		*out = new(v2.LoadBalancerScheme)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.IdleTimeoutClient != nil {
		in, out := &in.IdleTimeoutClient, &out.IdleTimeoutClient
		*out = new(int32)
		**out = **in
	}
	if in.IdleTimeoutMember != nil {
		in, out := &in.IdleTimeoutMember, &out.IdleTimeoutMember
		*out = new(int32)
		**out = **in
	}
	if in.IdleTimeoutConnection != nil {
		in, out := &in.IdleTimeoutConnection, &out.IdleTimeoutConnection
		*out = new(int32)
		**out = **in
	}
	if in.InboundCIDRs != nil {
		in, out := &in.InboundCIDRs, &out.InboundCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PoolAlgorithm != nil {
		in, out := &in.PoolAlgorithm, &out.PoolAlgorithm
		*out = new(v2.PoolAlgorithm)
		**out = **in
	}
	if in.EnableAutoscale != nil {
		in, out := &in.EnableAutoscale, &out.EnableAutoscale
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TargetNodeLabels != nil {
		in, out := &in.TargetNodeLabels, &out.TargetNodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IsPoc != nil {
		in, out := &in.IsPoc, &out.IsPoc
		*out = new(bool)
		**out = **in
	}
	if in.PreferZoneID != nil {
		in, out := &in.PreferZoneID, &out.PreferZoneID
		*out = new(string)
		**out = **in
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]Listener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]Pool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkLoadBalancerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = new(ApplicationLoadBalancerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AttachSecurityGroupsToNodes != nil {
		in, out := &in.AttachSecurityGroupsToNodes, &out.AttachSecurityGroupsToNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoManageSecurityGroupRules != nil {
		in, out := &in.AutoManageSecurityGroupRules, &out.AutoManageSecurityGroupRules
		*out = make([]SecurityGroupRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudLoadBalancerConfigSpec.
func (in *VngcloudLoadBalancerConfigSpec) DeepCopy() *VngcloudLoadBalancerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VngcloudLoadBalancerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VngcloudLoadBalancerConfigStatus) DeepCopyInto(out *VngcloudLoadBalancerConfigStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ManagePools != nil {
		in, out := &in.ManagePools, &out.ManagePools
		*out = new(bool)
		**out = **in
	}
	if in.ManageListeners != nil {
		in, out := &in.ManageListeners, &out.ManageListeners
		*out = new(bool)
		**out = **in
	}
	if in.ManageDFPMembers != nil {
		in, out := &in.ManageDFPMembers, &out.ManageDFPMembers
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VngcloudLoadBalancerConfigStatus.
func (in *VngcloudLoadBalancerConfigStatus) DeepCopy() *VngcloudLoadBalancerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(VngcloudLoadBalancerConfigStatus)
	in.DeepCopyInto(out)
	return out
}
