package builder

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"unicode"

	"github.com/sirupsen/logrus"
	loadbalancerv2 "github.com/vngcloud/vngcloud-go-sdk/v2/vngcloud/services/loadbalancer/v2"
	"github.com/vngcloud/vngcloud-load-balancer-controller/pkg/annotations"
	"github.com/vngcloud/vngcloud-load-balancer-controller/pkg/consts"
	"github.com/vngcloud/vngcloud-load-balancer-controller/pkg/errs"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/labels"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type TargetType string

const (
	TargetTypeInstance TargetType = "instance"
	TargetTypeIP       TargetType = "ip"
)

type MemberAddress struct {
	IP   string
	Name string
}

type LoadbalancerBuilder interface {
	// // Get the name generated by default
	// GetDefaultName() string
	// Get the current name of the Load Balancer
	GetName() string

	// Get the ID of the Load Balancer
	GetID() string
	GetPackageID() string
	GetTags() map[string]string
	GetSecurityGroupIDs() []string

	IsIgnored() bool
	// It mays create lb, listener, pool (not policy) at the same time
	CreateLoadBalancerOptions() loadbalancerv2.ICreateLoadBalancerRequest

	// default subnet id of the network if not specified
	GetSubnetID() (subnetID string)
	GetNetworkID() (networkID string)

	GetTargetNodeLabels() map[string]string
	GetTargetType() TargetType

	StringFormat() string
	JSONFormat() string
	Print()

	// GetPoolBuilders() []PoolBuilder
	// GetPoolBuilderByName(name string) PoolBuilder

	AddPoolBuilder(pool *poolBuilderType)
	GetPoolBuilders() []*poolBuilderType
	GetPoolBuilderByName(name string) *poolBuilderType
	GetPoolBuilderByID(name string) *poolBuilderType

	AddListenerBuilder(listener *ListenerBuilderType)
	GetListenerBuilders() []*ListenerBuilderType
	GetListenerBuilderByName(name string) *ListenerBuilderType
	GetListenerBuilderByPort(port int) *ListenerBuilderType
	// return true if the pool is used by other listener, which is not deleted
	IsPoolInUseByOtherListener(poolID string) bool

	// after create listener, use this function to update current builder
	AddCloneListenerBuilder(listener *ListenerBuilderType)
}

var _ LoadbalancerBuilder = &lbBuilder{}

type lbBuilder struct {
	// annotation configuration
	isIgnored                  bool
	loadBalancerID             string
	loadBalancerName           string
	loadBalancerType           loadbalancerv2.LoadBalancerType
	packageID                  string
	scheme                     loadbalancerv2.LoadBalancerScheme
	idleTimeoutClient          int
	idleTimeoutMember          int
	idleTimeoutConnection      int
	inboundCIDRs               []string
	healthcheckProtocol        loadbalancerv2.HealthCheckProtocol
	healthcheckPath            string
	successCodes               string
	healthcheckHttpVersion     loadbalancerv2.HealthCheckHttpVersion
	healthcheckHttpDomainName  string
	healthyThresholdCount      int
	unhealthyThresholdCount    int
	poolAlgorithm              loadbalancerv2.PoolAlgorithm
	tags                       map[string]string
	targetNodeLabels           map[string]string
	securityGroups             []string
	healthcheckPort            int
	healthcheckHttpMethod      loadbalancerv2.HealthCheckMethod
	healthcheckTimeoutSeconds  int
	healthcheckIntervalSeconds int
	enableAutoscale            bool
	targetType                 TargetType

	// annotation configuration for L4 only
	enableProxyProtocol []string

	// annotation configuration for L7 only
	enableStickySession bool
	enableTLSEncryption bool
	certificateIDs      []string

	// helper components
	annotationParser annotations.Parser
	context          context.Context
	client           client.Client
	logger           *logrus.Entry

	networkID  string
	subnetID   string
	subnetCIDR string
	clusterID  string

	// load balancer info
	poolBuilders         []*poolBuilderType
	listenerBuilders     []*ListenerBuilderType
	secGroupRuleBuilders []*secGroupRuleBuilderType

	// resource info
	resourceType      string // service, ingress
	resourceName      string
	resourceNamespace string

	// if user pass the security group annotation, don't create any security group, just use the given security group
	IsAutoCreateSecurityGroup bool
}

func (l *lbBuilder) GetName() string {
	return l.loadBalancerName
}

func (l *lbBuilder) GetID() string {
	return l.loadBalancerID
}

func (l *lbBuilder) GetPackageID() string {
	return l.packageID
}

func (l *lbBuilder) GetTags() map[string]string {
	return l.tags
}

func (l *lbBuilder) GetSecurityGroupIDs() []string {
	return l.securityGroups
}

func (l *lbBuilder) IsIgnored() bool {
	return l.isIgnored
}

func (l *lbBuilder) CreateLoadBalancerOptions() loadbalancerv2.ICreateLoadBalancerRequest {
	opts := loadbalancerv2.NewCreateLoadBalancerRequest(l.GetName(), l.GetPackageID(), l.GetSubnetID()).
		WithScheme(l.scheme).
		WithType(l.loadBalancerType)

	// if have pool, create first pool, but in L7, only create default pool in this step
	if len(l.GetPoolBuilders()) > 0 {
		poolBuilder := l.GetPoolBuilders()[0]
		if poolBuilder.IsL4 || (!poolBuilder.IsL4 && poolBuilder.GetName() == consts.DEFAULT_NAME_DEFAULT_POOL) {
			// Both listener and pool properties must be required (non null) or both are not required (null); <nil> map[]},
			// if have listener, create first listener
			if len(l.GetListenerBuilders()) > 0 {
				listenerBuilder := l.GetListenerBuilders()[0]
				opts.WithListener(
					listenerBuilder.GetICreateListenerRequest(),
				)
				opts.WithPool(poolBuilder.GetICreatePoolRequest(""))
			}
		}
	}

	// if have tags, add tags
	// ............................
	return opts
}

func (l *lbBuilder) GetNetworkID() string {
	return l.networkID
}

func (l *lbBuilder) GetSubnetID() string {
	return l.subnetID
}

func (l *lbBuilder) GetTargetNodeLabels() map[string]string {
	return l.targetNodeLabels
}

func (l *lbBuilder) GetTargetType() TargetType {
	return l.targetType
}

func (l *lbBuilder) StringFormat() string {
	return fmt.Sprintf("%+v", l)
}

func (l *lbBuilder) JSONFormat() string {
	b, err := json.MarshalIndent(l, "", "  ")
	if err != nil {
		return "Error while marshalling"
	}
	return string(b)
}

func (l *lbBuilder) Print() {
	l.logger.Info(l.JSONFormat())
	// l.logger.Info(l.poolBuilders)
	// l.logger.Info(l.listenerBuilders)
}

func (l *lbBuilder) AddPoolBuilder(pool *poolBuilderType) {
	for _, p := range l.poolBuilders {
		if p.GetName() == pool.GetName() {
			return
		}
	}
	l.poolBuilders = append(l.poolBuilders, pool)
}

func (l *lbBuilder) GetPoolBuilders() []*poolBuilderType {
	return l.poolBuilders
}

func (l *lbBuilder) GetPoolBuilderByName(name string) *poolBuilderType {
	for _, pool := range l.poolBuilders {
		if pool.GetName() == name {
			return pool
		}
	}
	return nil
}

func (l *lbBuilder) GetPoolBuilderByID(id string) *poolBuilderType {
	for _, pool := range l.poolBuilders {
		if pool.GetID() == id {
			return pool
		}
	}
	return nil
}

func (l *lbBuilder) AddListenerBuilder(listener *ListenerBuilderType) {
	for _, l := range l.listenerBuilders {
		if l.GetName() == listener.GetName() {
			return
		}
	}
	l.listenerBuilders = append(l.listenerBuilders, listener)
}

func (l *lbBuilder) GetListenerBuilders() []*ListenerBuilderType {
	return l.listenerBuilders
}

func (l *lbBuilder) GetListenerBuilderByName(name string) *ListenerBuilderType {
	for _, listener := range l.listenerBuilders {
		if listener.GetName() == name {
			return listener
		}
	}
	return nil
}

func (l *lbBuilder) GetListenerBuilderByPort(port int) *ListenerBuilderType {
	for _, listener := range l.listenerBuilders {
		if listener.ListenerProtocolPort == port {
			return listener
		}
	}
	return nil
}

func (l *lbBuilder) IsPoolInUseByOtherListener(poolID string) bool {
	// check if the pool is used by other listener
	for _, listener := range l.listenerBuilders {
		if !listener.IsDeleted() && *listener.DefaultPoolId == poolID {
			return true
		}

		if listener.IsDeleted() {
			continue
		}

		// check if the pool is used by policy
		for _, policy := range listener.GetPolicyBuilders() {
			if !policy.IsDeleted() && policy.RedirectPoolID == poolID {
				return true
			}
		}
	}
	return false
}

func (l *lbBuilder) AddCloneListenerBuilder(listener *ListenerBuilderType) {
	clone := &ListenerBuilderType{
		commonBuilder: commonBuilder{
			name: listener.GetName(),
			id:   listener.GetID(),
		},
		isDeleted:      false,
		policyBuilders: make([]*policyBuilderType, 0),
		CreateListenerRequest: loadbalancerv2.CreateListenerRequest{
			AllowedCidrs:                listener.CreateListenerRequest.AllowedCidrs,
			ListenerName:                listener.CreateListenerRequest.ListenerName,
			ListenerProtocol:            listener.CreateListenerRequest.ListenerProtocol,
			ListenerProtocolPort:        listener.CreateListenerRequest.ListenerProtocolPort,
			TimeoutClient:               listener.CreateListenerRequest.TimeoutClient,
			TimeoutConnection:           listener.CreateListenerRequest.TimeoutConnection,
			TimeoutMember:               listener.CreateListenerRequest.TimeoutMember,
			DefaultPoolId:               listener.CreateListenerRequest.DefaultPoolId,
			CertificateAuthorities:      listener.CreateListenerRequest.CertificateAuthorities,
			ClientCertificate:           listener.CreateListenerRequest.ClientCertificate,
			DefaultCertificateAuthority: listener.CreateListenerRequest.DefaultCertificateAuthority,
		},
		ReferPoolName: listener.ReferPoolName,
		IsL4:          listener.IsL4,
	}
	l.listenerBuilders = append(l.listenerBuilders, clone)
}

// ---------------------------------------------------------- generate name

func (l *lbBuilder) objectToLBName() string {
	hash := l.generateHash()
	name := fmt.Sprintf("%s_%s_%s_%s_%s",
		consts.DEFAULT_LB_PREFIX_NAME,
		TrimString(l.clusterID, 10),
		TrimString(l.resourceNamespace, 10),
		TrimString(l.resourceName, 10),
		hash)
	return l.validateName(name)
}

func (l *lbBuilder) generateHash() string {
	fullName := fmt.Sprintf("%s_%s_%s_%s", l.clusterID, l.resourceNamespace, l.resourceName, l.resourceType)
	hash := HashString(fullName)
	return TrimString(hash, consts.DEFAULT_HASH_NAME_LENGTH)
}

func (l *lbBuilder) validateName(newName string) string {
	for _, char := range newName {
		if !unicode.IsLetter(char) && !unicode.IsDigit(char) && char != '-' && char != '.' {
			newName = strings.ReplaceAll(newName, string(char), "-")
		}
	}
	if len(newName) > consts.DEFAULT_PORTAL_NAME_LENGTH {
		logrus.Warnf("The name %s is too long, it will be truncated", newName)
	}
	return TrimString(newName, consts.DEFAULT_PORTAL_NAME_LENGTH)
}

// mappingProtocol maps the protocol TCP to the protocol PROXY if have configured.
func (l *lbBuilder) mappingProtocol(pPort corev1.ServicePort) string {
	for _, name := range l.enableProxyProtocol {
		if (name == "*" || name == pPort.Name) && pPort.Protocol == corev1.ProtocolTCP {
			return string(loadbalancerv2.PoolProtocolProxy)
		}
	}
	return string(pPort.Protocol)
}

// genL4ListenerName generates the name of the listener.
func (l *lbBuilder) genL4ListenerName(pPort corev1.ServicePort) string {
	hash := l.generateHash()
	name := fmt.Sprintf("%s_%s_%s_%s_%s_%s_%d",
		consts.DEFAULT_LB_PREFIX_NAME,
		TrimString(l.clusterID, 10),
		TrimString(l.resourceNamespace, 9),
		TrimString(l.resourceName, 9),
		hash,
		TrimString(string(pPort.Protocol), 3),
		pPort.Port)
	return l.validateName(name)
}

// genL4PoolName generates the name of the pool.
func (l *lbBuilder) genL4PoolName(pPort corev1.ServicePort) string {
	realProtocol := l.mappingProtocol(pPort)

	hash := l.generateHash()
	name := fmt.Sprintf("%s_%s_%s_%s_%s_%s_%d",
		consts.DEFAULT_LB_PREFIX_NAME,
		TrimString(l.clusterID, 10),
		TrimString(l.resourceNamespace, 9),
		TrimString(l.resourceName, 9),
		hash,
		TrimString(realProtocol, 3),
		pPort.Port)
	return l.validateName(name)
}

// ---------------------------------------------------------- node k8s

// filterByNodeLabel filters the given list of nodes by the given node labels.
func (l *lbBuilder) filterByNodeLabel(nodes []*corev1.Node, nodeLabels map[string]string) []*corev1.Node {
	var filtered []*corev1.Node
	for _, node := range nodes {
		if node == nil {
			continue
		}
		if node.Labels == nil {
			continue
		}
		if labels.Set(nodeLabels).AsSelector().Matches(labels.Set(node.Labels)) {
			filtered = append(filtered, node)
		}
	}
	return filtered
}

// getNodeMembersAddr returns array internal IP address of the nodes.
func (l *lbBuilder) getNodeMembersAddr(nodeObjs []*corev1.Node) []*MemberAddress {
	nodeAddr := make([]*MemberAddress, 0)
	for _, node := range nodeObjs {
		addr, err := l.getNodeInternalAddress(node)
		if err != nil {
			l.logger.Warnf("Failed to get internal IP address of node %s: %v, continue.", node.Name, err)
			continue
		}
		nodeAddr = append(nodeAddr, &MemberAddress{IP: addr, Name: node.Name})
	}
	return nodeAddr
}

// getNodeInternalAddress returns the internal IP address of the node.
func (l *lbBuilder) getNodeInternalAddress(node *corev1.Node) (string, error) {
	addrs := node.Status.Addresses
	if len(addrs) == 0 {
		return "", errs.ErrorNodeNotHaveInternalIP
	}
	for _, addr := range addrs {
		if addr.Type == corev1.NodeInternalIP {
			return addr.Address, nil
		}
	}
	return addrs[0].Address, nil
}

// ---------------------------------------------------------- endpoint k8s

// getEndpointMembersAddr returns array internal IP address of the endpoint.
func (l *lbBuilder) getEndpointMembersAddr(namespace, name string) ([]*MemberAddress, error) {
	endpoint := &corev1.Endpoints{}
	err := l.client.Get(l.context, client.ObjectKey{Namespace: namespace, Name: name}, endpoint)
	if err != nil {
		l.logger.Errorf("Failed to get endpoint %s/%s: %v", namespace, name, err)
		return nil, err
	}
	addrs := make([]*MemberAddress, 0)
	for _, subset := range endpoint.Subsets {
		for _, addr := range subset.Addresses {
			addrs = append(addrs, &MemberAddress{IP: addr.IP, Name: addr.TargetRef.Name})
		}
		for _, addr := range subset.NotReadyAddresses {
			addrs = append(addrs, &MemberAddress{IP: addr.IP, Name: addr.TargetRef.Name})
		}
	}
	return addrs, nil
}

// ---------------------------------------------------------- secgroup

// addSecgroupRule adds a security group rule to the list.
func (l *lbBuilder) addSecgroupRule(port int, protocol string) {
	protocolType := ProtocolTypeTCP
	p := strings.ToLower(protocol)
	switch p {
	case "udp":
		protocolType = ProtocolTypeUDP
	case "icmp":
		protocolType = ProtocolTypeICMP
	default:
		protocolType = ProtocolTypeTCP
	}
	isExist := false
	for _, rule := range l.secGroupRuleBuilders {
		if rule.GetPortRangeMax() == port &&
			rule.GetPortRangeMin() == port &&
			rule.GetProtocol() == protocolType {
			isExist = true
			break
		}
	}
	if !isExist {
		l.secGroupRuleBuilders = append(l.secGroupRuleBuilders, &secGroupRuleBuilderType{
			Protocol:     protocolType,
			PortRangeMin: port,
			PortRangeMax: port,
		})
	}
}

// func (l *lbBuilder)
// func (l *lbBuilder)
// func (l *lbBuilder)
// func (l *lbBuilder)
// func (l *lbBuilder)
// func (l *lbBuilder)
// func (l *lbBuilder)
// func (l *lbBuilder)
// func (l *lbBuilder)
// func (l *lbBuilder)
// func (l *lbBuilder)
