package builder

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"unicode"

	"github.com/sirupsen/logrus"
	loadbalancerv2 "github.com/vngcloud/vngcloud-go-sdk/v2/vngcloud/services/loadbalancer/v2"
	"github.com/vngcloud/vngcloud-load-balancer-controller/pkg/annotations"
	"github.com/vngcloud/vngcloud-load-balancer-controller/pkg/consts"
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type TargetType string

const (
	TargetTypeInstance TargetType = "instance"
	TargetTypeIP       TargetType = "ip"
)

type MemberAddress struct {
	IP   string
	Name string
}

// just build the model, use to compare with the real load balancer
type ModelBuilder interface {
	// // Get the name generated by default
	// GetDefaultName() string
	// Get the current name of the Load Balancer
	GetName() string

	// Get the ID of the Load Balancer
	GetID() string
	GetPackageID() string
	GetTags() map[string]string
	GetSecurityGroupIDs() []string

	IsIgnored() bool
	// It mays create lb, listener, pool (not policy) at the same time
	CreateLoadBalancerOptions() loadbalancerv2.ICreateLoadBalancerRequest

	// default subnet id of the network if not specified
	GetSubnetID() (subnetID string)
	GetNetworkID() (networkID string)

	GetTargetNodeLabels() map[string]string
	GetTargetType() TargetType

	StringFormat() string
	JSONFormat() string
	Print()

	// GetPoolBuilders() []PoolBuilder
	// GetPoolBuilderByName(name string) PoolBuilder

	AddPoolBuilder(pool *poolBuilderType)
	GetPoolBuilders() []*poolBuilderType
	GetPoolBuilderByName(name string) *poolBuilderType
	GetPoolBuilderByID(name string) *poolBuilderType

	AddListenerBuilder(listener *ListenerBuilderType)
	GetListenerBuilders() []*ListenerBuilderType
	GetListenerBuilderByName(name string) *ListenerBuilderType
	GetListenerBuilderByPort(port int) *ListenerBuilderType

	GetManageAnnotation() map[string]string
}

var _ ModelBuilder = &modelBuilder{}

type modelBuilder struct {
	// annotation configuration
	isIgnored                  bool
	idleTimeoutClient          int
	idleTimeoutMember          int
	idleTimeoutConnection      int
	inboundCIDRs               []string
	healthcheckProtocol        loadbalancerv2.HealthCheckProtocol
	healthcheckPath            string
	successCodes               string
	healthcheckHttpVersion     loadbalancerv2.HealthCheckHttpVersion
	healthcheckHttpDomainName  string
	healthyThresholdCount      int
	unhealthyThresholdCount    int
	poolAlgorithm              loadbalancerv2.PoolAlgorithm
	targetNodeLabels           map[string]string
	securityGroups             []string
	healthcheckPort            int
	healthcheckHttpMethod      loadbalancerv2.HealthCheckMethod
	healthcheckTimeoutSeconds  int
	healthcheckIntervalSeconds int
	enableAutoscale            bool
	targetType                 TargetType

	// annotation configuration for L4 only
	enableProxyProtocol []string

	// annotation configuration for L7 only
	enableStickySession bool
	enableTLSEncryption bool
	certificateIDs      []string

	// helper components
	annotationParser annotations.Parser
	context          context.Context
	client           client.Client
	logger           *logrus.Entry

	networkID  string
	subnetID   string
	subnetCIDR string
	clusterID  string

	secGroupRuleBuilders []*secGroupRuleBuilderType

	// resource info
	resourceType      string // service, ingress
	resourceName      string
	resourceNamespace string

	// if user pass the security group annotation, don't create any security group, just use the given security group
	IsAutoCreateSecurityGroup bool

	poolListenerHelper
	basicInfoHelper
}

func (l *modelBuilder) GetName() string {
	return l.loadBalancerName
}

func (l *modelBuilder) GetID() string {
	return l.loadBalancerID
}

func (l *modelBuilder) GetPackageID() string {
	return l.packageID
}

func (l *modelBuilder) GetTags() map[string]string {
	return l.basicInfoHelper.GetTags()
}

func (l *modelBuilder) GetSecurityGroupIDs() []string {
	return l.securityGroups
}

func (l *modelBuilder) IsIgnored() bool {
	return l.isIgnored
}

func (l *modelBuilder) CreateLoadBalancerOptions() loadbalancerv2.ICreateLoadBalancerRequest {
	opts := loadbalancerv2.NewCreateLoadBalancerRequest(l.GetName(), l.GetPackageID(), l.GetSubnetID()).
		WithScheme(l.scheme).
		WithType(l.loadBalancerType)

	// if have pool, create first pool, but in L7, only create default pool in this step
	if len(l.GetPoolBuilders()) > 0 {
		poolBuilder := l.GetPoolBuilders()[0]
		if poolBuilder.IsL4 || (!poolBuilder.IsL4 && poolBuilder.GetName() == consts.DEFAULT_NAME_DEFAULT_POOL) {
			// Both listener and pool properties must be required (non null) or both are not required (null); <nil> map[]},
			// if have listener, create first listener
			if len(l.GetListenerBuilders()) > 0 {
				listenerBuilder := l.GetListenerBuilders()[0]
				opts.WithListener(
					listenerBuilder.GetICreateListenerRequest(),
				)
				opts.WithPool(poolBuilder.GetICreatePoolRequest(""))
			}
		}
	}

	// if have tags, add tags
	// ............................
	return opts
}

func (l *modelBuilder) GetNetworkID() string {
	return l.networkID
}

func (l *modelBuilder) GetSubnetID() string {
	return l.subnetID
}

func (l *modelBuilder) GetTargetNodeLabels() map[string]string {
	return l.targetNodeLabels
}

func (l *modelBuilder) GetTargetType() TargetType {
	return l.targetType
}

func (l *modelBuilder) StringFormat() string {
	return fmt.Sprintf("%+v", l)
}

func (l *modelBuilder) JSONFormat() string {
	b, err := json.MarshalIndent(l, "", "  ")
	if err != nil {
		return "Error while marshalling"
	}
	return string(b)
}

func (l *modelBuilder) Print() {
	l.logger.Info(l.JSONFormat())
	// l.logger.Info(l.poolBuilders)
	// l.logger.Info(l.listenerBuilders)
}

func (l *modelBuilder) GetManageAnnotation() map[string]string {
	poolInfos := make([]string, 0)
	for _, pool := range l.GetPoolBuilders() {
		if pool.IsDeleted() {
			continue
		}
		if pool.GetName() == "" || pool.GetID() == "" {
			l.logger.Warnf("Pool name: %s, ID: %s is empty.", pool.GetName(), pool.GetID())
		}
		poolInfos = append(poolInfos, fmt.Sprintf("%s:%s", pool.GetID(), pool.GetName()))
	}

	listenerInfos := make([]string, 0)
	for _, listener := range l.GetListenerBuilders() {
		if listener.IsDeleted() {
			continue
		}
		if listener.GetName() == "" || listener.GetID() == "" {
			l.logger.Warnf("Listener name: %s, ID: %s is empty.", listener.GetName(), listener.GetID())
		}
		policyInfos := make([]string, 0)
		for _, policy := range listener.GetPolicyBuilders() {
			if policy.IsDeleted() {
				continue
			}
			if policy.GetName() == "" {
				l.logger.Warnf("Policy name is empty.")
			}
			policyInfos = append(policyInfos, policy.GetName())
		}
		listenerInfos = append(listenerInfos, fmt.Sprintf("%s:%s:[%s]", listener.GetID(), listener.GetName(), strings.Join(policyInfos, "|")))
	}

	defaultPoolMembers := []string{}
	defaultPool := l.GetPoolBuilderByName(consts.DEFAULT_NAME_DEFAULT_POOL)
	if defaultPool != nil {
		for _, member := range defaultPool.Members {
			defaultPoolMembers = append(defaultPoolMembers,
				fmt.Sprintf("%s:%d:%d", member.IpAddress, member.Port, member.MonitorPort))
		}
	}

	return map[string]string{
		fmt.Sprintf("%s/%s", l.annotationParser.GetPrefix(), annotations.SuffixManagePools):      strings.Join(poolInfos, ","),
		fmt.Sprintf("%s/%s", l.annotationParser.GetPrefix(), annotations.SuffixManageListeners):  strings.Join(listenerInfos, ","),
		fmt.Sprintf("%s/%s", l.annotationParser.GetPrefix(), annotations.SuffixManageDFPMembers): strings.Join(defaultPoolMembers, ","),
	}
}

// ---------------------------------------------------------- generate name

func (l *modelBuilder) objectToLBName() string {
	hash := l.generateHash()
	name := fmt.Sprintf("%s_%s_%s_%s_%s",
		consts.DEFAULT_LB_PREFIX_NAME,
		TrimString(l.clusterID, 10),
		TrimString(l.resourceNamespace, 10),
		TrimString(l.resourceName, 10),
		hash)
	return l.validateName(name)
}

func (l *modelBuilder) generateHash() string {
	fullName := fmt.Sprintf("%s_%s_%s_%s", l.clusterID, l.resourceNamespace, l.resourceName, l.resourceType)
	hash := HashString(fullName)
	return TrimString(hash, consts.DEFAULT_HASH_NAME_LENGTH)
}

func (l *modelBuilder) validateName(newName string) string {
	for _, char := range newName {
		if !unicode.IsLetter(char) && !unicode.IsDigit(char) && char != '-' && char != '.' {
			newName = strings.ReplaceAll(newName, string(char), "-")
		}
	}
	if len(newName) > consts.DEFAULT_PORTAL_NAME_LENGTH {
		logrus.Warnf("The name %s is too long, it will be truncated", newName)
	}
	return TrimString(newName, consts.DEFAULT_PORTAL_NAME_LENGTH)
}

// mappingProtocol maps the protocol TCP to the protocol PROXY if have configured.
func (l *modelBuilder) mappingProtocol(pPort corev1.ServicePort) string {
	for _, name := range l.enableProxyProtocol {
		if (name == "*" || name == pPort.Name) && pPort.Protocol == corev1.ProtocolTCP {
			return string(loadbalancerv2.PoolProtocolProxy)
		}
	}
	return string(pPort.Protocol)
}

// genL4ListenerName generates the name of the listener.
func (l *modelBuilder) genL4ListenerName(pPort corev1.ServicePort) string {
	hash := l.generateHash()
	name := fmt.Sprintf("%s_%s_%s_%s_%s_%s_%d",
		consts.DEFAULT_LB_PREFIX_NAME,
		TrimString(l.clusterID, 10),
		TrimString(l.resourceNamespace, 9),
		TrimString(l.resourceName, 9),
		hash,
		TrimString(string(pPort.Protocol), 3),
		pPort.Port)
	return l.validateName(name)
}

// genL4PoolName generates the name of the pool.
func (l *modelBuilder) genL4PoolName(pPort corev1.ServicePort) string {
	realProtocol := l.mappingProtocol(pPort)

	hash := l.generateHash()
	name := fmt.Sprintf("%s_%s_%s_%s_%s_%s_%d",
		consts.DEFAULT_LB_PREFIX_NAME,
		TrimString(l.clusterID, 10),
		TrimString(l.resourceNamespace, 9),
		TrimString(l.resourceName, 9),
		hash,
		TrimString(realProtocol, 3),
		pPort.Port)
	return l.validateName(name)
}

// func (l *modelBuilder)
// func (l *modelBuilder)
// func (l *modelBuilder)
// func (l *modelBuilder)
// func (l *modelBuilder)
// func (l *modelBuilder)
// func (l *modelBuilder)
// func (l *modelBuilder)
// func (l *modelBuilder)
// func (l *modelBuilder)
// func (l *modelBuilder)
