// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime"
)

// NewMockIServiceUseCase creates a new instance of MockIServiceUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServiceUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServiceUseCase {
	mock := &MockIServiceUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIServiceUseCase is an autogenerated mock type for the IServiceUseCase type
type MockIServiceUseCase struct {
	mock.Mock
}

type MockIServiceUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServiceUseCase) EXPECT() *MockIServiceUseCase_Expecter {
	return &MockIServiceUseCase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockIServiceUseCase
func (_mock *MockIServiceUseCase) Delete(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIServiceUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockIServiceUseCase_Expecter) Delete(ctx interface{}, req interface{}) *MockIServiceUseCase_Delete_Call {
	return &MockIServiceUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockIServiceUseCase_Delete_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockIServiceUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceUseCase_Delete_Call) Return(err error) *MockIServiceUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockIServiceUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Ensure provides a mock function for the type MockIServiceUseCase
func (_mock *MockIServiceUseCase) Ensure(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceUseCase_Ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ensure'
type MockIServiceUseCase_Ensure_Call struct {
	*mock.Call
}

// Ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockIServiceUseCase_Expecter) Ensure(ctx interface{}, req interface{}) *MockIServiceUseCase_Ensure_Call {
	return &MockIServiceUseCase_Ensure_Call{Call: _e.mock.On("Ensure", ctx, req)}
}

func (_c *MockIServiceUseCase_Ensure_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockIServiceUseCase_Ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIServiceUseCase_Ensure_Call) Return(err error) *MockIServiceUseCase_Ensure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceUseCase_Ensure_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockIServiceUseCase_Ensure_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockIServiceUseCase
func (_mock *MockIServiceUseCase) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServiceUseCase_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockIServiceUseCase_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIServiceUseCase_Expecter) Init(ctx interface{}) *MockIServiceUseCase_Init_Call {
	return &MockIServiceUseCase_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockIServiceUseCase_Init_Call) Run(run func(ctx context.Context)) *MockIServiceUseCase_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIServiceUseCase_Init_Call) Return(err error) *MockIServiceUseCase_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServiceUseCase_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockIServiceUseCase_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIVLBConfigUseCase creates a new instance of MockIVLBConfigUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIVLBConfigUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIVLBConfigUseCase {
	mock := &MockIVLBConfigUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIVLBConfigUseCase is an autogenerated mock type for the IVLBConfigUseCase type
type MockIVLBConfigUseCase struct {
	mock.Mock
}

type MockIVLBConfigUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIVLBConfigUseCase) EXPECT() *MockIVLBConfigUseCase_Expecter {
	return &MockIVLBConfigUseCase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockIVLBConfigUseCase
func (_mock *MockIVLBConfigUseCase) Delete(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIVLBConfigUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIVLBConfigUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockIVLBConfigUseCase_Expecter) Delete(ctx interface{}, req interface{}) *MockIVLBConfigUseCase_Delete_Call {
	return &MockIVLBConfigUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockIVLBConfigUseCase_Delete_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockIVLBConfigUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIVLBConfigUseCase_Delete_Call) Return(err error) *MockIVLBConfigUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIVLBConfigUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockIVLBConfigUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Ensure provides a mock function for the type MockIVLBConfigUseCase
func (_mock *MockIVLBConfigUseCase) Ensure(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIVLBConfigUseCase_Ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ensure'
type MockIVLBConfigUseCase_Ensure_Call struct {
	*mock.Call
}

// Ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockIVLBConfigUseCase_Expecter) Ensure(ctx interface{}, req interface{}) *MockIVLBConfigUseCase_Ensure_Call {
	return &MockIVLBConfigUseCase_Ensure_Call{Call: _e.mock.On("Ensure", ctx, req)}
}

func (_c *MockIVLBConfigUseCase_Ensure_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockIVLBConfigUseCase_Ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIVLBConfigUseCase_Ensure_Call) Return(err error) *MockIVLBConfigUseCase_Ensure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIVLBConfigUseCase_Ensure_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockIVLBConfigUseCase_Ensure_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockIVLBConfigUseCase
func (_mock *MockIVLBConfigUseCase) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIVLBConfigUseCase_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockIVLBConfigUseCase_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIVLBConfigUseCase_Expecter) Init(ctx interface{}) *MockIVLBConfigUseCase_Init_Call {
	return &MockIVLBConfigUseCase_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockIVLBConfigUseCase_Init_Call) Run(run func(ctx context.Context)) *MockIVLBConfigUseCase_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIVLBConfigUseCase_Init_Call) Return(err error) *MockIVLBConfigUseCase_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIVLBConfigUseCase_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockIVLBConfigUseCase_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNodeSecurityGroupUseCase creates a new instance of MockNodeSecurityGroupUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeSecurityGroupUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeSecurityGroupUseCase {
	mock := &MockNodeSecurityGroupUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeSecurityGroupUseCase is an autogenerated mock type for the NodeSecurityGroupUseCase type
type MockNodeSecurityGroupUseCase struct {
	mock.Mock
}

type MockNodeSecurityGroupUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeSecurityGroupUseCase) EXPECT() *MockNodeSecurityGroupUseCase_Expecter {
	return &MockNodeSecurityGroupUseCase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) Delete(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNodeSecurityGroupUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockNodeSecurityGroupUseCase_Expecter) Delete(ctx interface{}, req interface{}) *MockNodeSecurityGroupUseCase_Delete_Call {
	return &MockNodeSecurityGroupUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockNodeSecurityGroupUseCase_Delete_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockNodeSecurityGroupUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Delete_Call) Return(err error) *MockNodeSecurityGroupUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockNodeSecurityGroupUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Ensure provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) Ensure(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_Ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ensure'
type MockNodeSecurityGroupUseCase_Ensure_Call struct {
	*mock.Call
}

// Ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockNodeSecurityGroupUseCase_Expecter) Ensure(ctx interface{}, req interface{}) *MockNodeSecurityGroupUseCase_Ensure_Call {
	return &MockNodeSecurityGroupUseCase_Ensure_Call{Call: _e.mock.On("Ensure", ctx, req)}
}

func (_c *MockNodeSecurityGroupUseCase_Ensure_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockNodeSecurityGroupUseCase_Ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Ensure_Call) Return(err error) *MockNodeSecurityGroupUseCase_Ensure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Ensure_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockNodeSecurityGroupUseCase_Ensure_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockNodeSecurityGroupUseCase_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNodeSecurityGroupUseCase_Expecter) Init(ctx interface{}) *MockNodeSecurityGroupUseCase_Init_Call {
	return &MockNodeSecurityGroupUseCase_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockNodeSecurityGroupUseCase_Init_Call) Run(run func(ctx context.Context)) *MockNodeSecurityGroupUseCase_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Init_Call) Return(err error) *MockNodeSecurityGroupUseCase_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockNodeSecurityGroupUseCase_Init_Call {
	_c.Call.Return(run)
	return _c
}
