// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime"
)

// NewMockServiceUseCase creates a new instance of MockServiceUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceUseCase {
	mock := &MockServiceUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceUseCase is an autogenerated mock type for the ServiceUseCase type
type MockServiceUseCase struct {
	mock.Mock
}

type MockServiceUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceUseCase) EXPECT() *MockServiceUseCase_Expecter {
	return &MockServiceUseCase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockServiceUseCase
func (_mock *MockServiceUseCase) Delete(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServiceUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockServiceUseCase_Expecter) Delete(ctx interface{}, req interface{}) *MockServiceUseCase_Delete_Call {
	return &MockServiceUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockServiceUseCase_Delete_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockServiceUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceUseCase_Delete_Call) Return(err error) *MockServiceUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockServiceUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Ensure provides a mock function for the type MockServiceUseCase
func (_mock *MockServiceUseCase) Ensure(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceUseCase_Ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ensure'
type MockServiceUseCase_Ensure_Call struct {
	*mock.Call
}

// Ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockServiceUseCase_Expecter) Ensure(ctx interface{}, req interface{}) *MockServiceUseCase_Ensure_Call {
	return &MockServiceUseCase_Ensure_Call{Call: _e.mock.On("Ensure", ctx, req)}
}

func (_c *MockServiceUseCase_Ensure_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockServiceUseCase_Ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceUseCase_Ensure_Call) Return(err error) *MockServiceUseCase_Ensure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceUseCase_Ensure_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockServiceUseCase_Ensure_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockServiceUseCase
func (_mock *MockServiceUseCase) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceUseCase_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockServiceUseCase_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceUseCase_Expecter) Init(ctx interface{}) *MockServiceUseCase_Init_Call {
	return &MockServiceUseCase_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockServiceUseCase_Init_Call) Run(run func(ctx context.Context)) *MockServiceUseCase_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceUseCase_Init_Call) Return(err error) *MockServiceUseCase_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceUseCase_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockServiceUseCase_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoadBalancerConfigUseCase creates a new instance of MockLoadBalancerConfigUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoadBalancerConfigUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoadBalancerConfigUseCase {
	mock := &MockLoadBalancerConfigUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoadBalancerConfigUseCase is an autogenerated mock type for the LoadBalancerConfigUseCase type
type MockLoadBalancerConfigUseCase struct {
	mock.Mock
}

type MockLoadBalancerConfigUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoadBalancerConfigUseCase) EXPECT() *MockLoadBalancerConfigUseCase_Expecter {
	return &MockLoadBalancerConfigUseCase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockLoadBalancerConfigUseCase
func (_mock *MockLoadBalancerConfigUseCase) Delete(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoadBalancerConfigUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLoadBalancerConfigUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockLoadBalancerConfigUseCase_Expecter) Delete(ctx interface{}, req interface{}) *MockLoadBalancerConfigUseCase_Delete_Call {
	return &MockLoadBalancerConfigUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockLoadBalancerConfigUseCase_Delete_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockLoadBalancerConfigUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_Delete_Call) Return(err error) *MockLoadBalancerConfigUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockLoadBalancerConfigUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Ensure provides a mock function for the type MockLoadBalancerConfigUseCase
func (_mock *MockLoadBalancerConfigUseCase) Ensure(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoadBalancerConfigUseCase_Ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ensure'
type MockLoadBalancerConfigUseCase_Ensure_Call struct {
	*mock.Call
}

// Ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockLoadBalancerConfigUseCase_Expecter) Ensure(ctx interface{}, req interface{}) *MockLoadBalancerConfigUseCase_Ensure_Call {
	return &MockLoadBalancerConfigUseCase_Ensure_Call{Call: _e.mock.On("Ensure", ctx, req)}
}

func (_c *MockLoadBalancerConfigUseCase_Ensure_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockLoadBalancerConfigUseCase_Ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_Ensure_Call) Return(err error) *MockLoadBalancerConfigUseCase_Ensure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_Ensure_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockLoadBalancerConfigUseCase_Ensure_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockLoadBalancerConfigUseCase
func (_mock *MockLoadBalancerConfigUseCase) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoadBalancerConfigUseCase_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockLoadBalancerConfigUseCase_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLoadBalancerConfigUseCase_Expecter) Init(ctx interface{}) *MockLoadBalancerConfigUseCase_Init_Call {
	return &MockLoadBalancerConfigUseCase_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockLoadBalancerConfigUseCase_Init_Call) Run(run func(ctx context.Context)) *MockLoadBalancerConfigUseCase_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_Init_Call) Return(err error) *MockLoadBalancerConfigUseCase_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockLoadBalancerConfigUseCase_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNodeSecurityGroupUseCase creates a new instance of MockNodeSecurityGroupUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeSecurityGroupUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeSecurityGroupUseCase {
	mock := &MockNodeSecurityGroupUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeSecurityGroupUseCase is an autogenerated mock type for the NodeSecurityGroupUseCase type
type MockNodeSecurityGroupUseCase struct {
	mock.Mock
}

type MockNodeSecurityGroupUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeSecurityGroupUseCase) EXPECT() *MockNodeSecurityGroupUseCase_Expecter {
	return &MockNodeSecurityGroupUseCase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) Delete(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNodeSecurityGroupUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockNodeSecurityGroupUseCase_Expecter) Delete(ctx interface{}, req interface{}) *MockNodeSecurityGroupUseCase_Delete_Call {
	return &MockNodeSecurityGroupUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockNodeSecurityGroupUseCase_Delete_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockNodeSecurityGroupUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Delete_Call) Return(err error) *MockNodeSecurityGroupUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockNodeSecurityGroupUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Ensure provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) Ensure(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_Ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ensure'
type MockNodeSecurityGroupUseCase_Ensure_Call struct {
	*mock.Call
}

// Ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockNodeSecurityGroupUseCase_Expecter) Ensure(ctx interface{}, req interface{}) *MockNodeSecurityGroupUseCase_Ensure_Call {
	return &MockNodeSecurityGroupUseCase_Ensure_Call{Call: _e.mock.On("Ensure", ctx, req)}
}

func (_c *MockNodeSecurityGroupUseCase_Ensure_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockNodeSecurityGroupUseCase_Ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Ensure_Call) Return(err error) *MockNodeSecurityGroupUseCase_Ensure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Ensure_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockNodeSecurityGroupUseCase_Ensure_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockNodeSecurityGroupUseCase_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNodeSecurityGroupUseCase_Expecter) Init(ctx interface{}) *MockNodeSecurityGroupUseCase_Init_Call {
	return &MockNodeSecurityGroupUseCase_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockNodeSecurityGroupUseCase_Init_Call) Run(run func(ctx context.Context)) *MockNodeSecurityGroupUseCase_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Init_Call) Return(err error) *MockNodeSecurityGroupUseCase_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockNodeSecurityGroupUseCase_Init_Call {
	_c.Call.Return(run)
	return _c
}
