// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime"
)

// NewMockServiceUseCase creates a new instance of MockServiceUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceUseCase {
	mock := &MockServiceUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceUseCase is an autogenerated mock type for the ServiceUseCase type
type MockServiceUseCase struct {
	mock.Mock
}

type MockServiceUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceUseCase) EXPECT() *MockServiceUseCase_Expecter {
	return &MockServiceUseCase_Expecter{mock: &_m.Mock}
}

// DeleteServiceUseCase provides a mock function for the type MockServiceUseCase
func (_mock *MockServiceUseCase) DeleteServiceUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServiceUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceUseCase_DeleteServiceUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServiceUseCase'
type MockServiceUseCase_DeleteServiceUseCase_Call struct {
	*mock.Call
}

// DeleteServiceUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockServiceUseCase_Expecter) DeleteServiceUseCase(ctx interface{}, req interface{}) *MockServiceUseCase_DeleteServiceUseCase_Call {
	return &MockServiceUseCase_DeleteServiceUseCase_Call{Call: _e.mock.On("DeleteServiceUseCase", ctx, req)}
}

func (_c *MockServiceUseCase_DeleteServiceUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockServiceUseCase_DeleteServiceUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceUseCase_DeleteServiceUseCase_Call) Return(err error) *MockServiceUseCase_DeleteServiceUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceUseCase_DeleteServiceUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockServiceUseCase_DeleteServiceUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureServiceUseCase provides a mock function for the type MockServiceUseCase
func (_mock *MockServiceUseCase) EnsureServiceUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureServiceUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceUseCase_EnsureServiceUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureServiceUseCase'
type MockServiceUseCase_EnsureServiceUseCase_Call struct {
	*mock.Call
}

// EnsureServiceUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockServiceUseCase_Expecter) EnsureServiceUseCase(ctx interface{}, req interface{}) *MockServiceUseCase_EnsureServiceUseCase_Call {
	return &MockServiceUseCase_EnsureServiceUseCase_Call{Call: _e.mock.On("EnsureServiceUseCase", ctx, req)}
}

func (_c *MockServiceUseCase_EnsureServiceUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockServiceUseCase_EnsureServiceUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceUseCase_EnsureServiceUseCase_Call) Return(err error) *MockServiceUseCase_EnsureServiceUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceUseCase_EnsureServiceUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockServiceUseCase_EnsureServiceUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitServiceUseCase provides a mock function for the type MockServiceUseCase
func (_mock *MockServiceUseCase) InitServiceUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitServiceUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceUseCase_InitServiceUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitServiceUseCase'
type MockServiceUseCase_InitServiceUseCase_Call struct {
	*mock.Call
}

// InitServiceUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceUseCase_Expecter) InitServiceUseCase(ctx interface{}) *MockServiceUseCase_InitServiceUseCase_Call {
	return &MockServiceUseCase_InitServiceUseCase_Call{Call: _e.mock.On("InitServiceUseCase", ctx)}
}

func (_c *MockServiceUseCase_InitServiceUseCase_Call) Run(run func(ctx context.Context)) *MockServiceUseCase_InitServiceUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceUseCase_InitServiceUseCase_Call) Return(err error) *MockServiceUseCase_InitServiceUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceUseCase_InitServiceUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockServiceUseCase_InitServiceUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoadBalancerConfigUseCase creates a new instance of MockLoadBalancerConfigUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoadBalancerConfigUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoadBalancerConfigUseCase {
	mock := &MockLoadBalancerConfigUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoadBalancerConfigUseCase is an autogenerated mock type for the LoadBalancerConfigUseCase type
type MockLoadBalancerConfigUseCase struct {
	mock.Mock
}

type MockLoadBalancerConfigUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoadBalancerConfigUseCase) EXPECT() *MockLoadBalancerConfigUseCase_Expecter {
	return &MockLoadBalancerConfigUseCase_Expecter{mock: &_m.Mock}
}

// DeleteLoadBalancerConfigUseCase provides a mock function for the type MockLoadBalancerConfigUseCase
func (_mock *MockLoadBalancerConfigUseCase) DeleteLoadBalancerConfigUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLoadBalancerConfigUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLoadBalancerConfigUseCase'
type MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call struct {
	*mock.Call
}

// DeleteLoadBalancerConfigUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockLoadBalancerConfigUseCase_Expecter) DeleteLoadBalancerConfigUseCase(ctx interface{}, req interface{}) *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call {
	return &MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call{Call: _e.mock.On("DeleteLoadBalancerConfigUseCase", ctx, req)}
}

func (_c *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call) Return(err error) *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureLoadBalancerConfigUseCase provides a mock function for the type MockLoadBalancerConfigUseCase
func (_mock *MockLoadBalancerConfigUseCase) EnsureLoadBalancerConfigUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureLoadBalancerConfigUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureLoadBalancerConfigUseCase'
type MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call struct {
	*mock.Call
}

// EnsureLoadBalancerConfigUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockLoadBalancerConfigUseCase_Expecter) EnsureLoadBalancerConfigUseCase(ctx interface{}, req interface{}) *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call {
	return &MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call{Call: _e.mock.On("EnsureLoadBalancerConfigUseCase", ctx, req)}
}

func (_c *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call) Return(err error) *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitLoadBalancerConfigUseCase provides a mock function for the type MockLoadBalancerConfigUseCase
func (_mock *MockLoadBalancerConfigUseCase) InitLoadBalancerConfigUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitLoadBalancerConfigUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitLoadBalancerConfigUseCase'
type MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call struct {
	*mock.Call
}

// InitLoadBalancerConfigUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLoadBalancerConfigUseCase_Expecter) InitLoadBalancerConfigUseCase(ctx interface{}) *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call {
	return &MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call{Call: _e.mock.On("InitLoadBalancerConfigUseCase", ctx)}
}

func (_c *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call) Run(run func(ctx context.Context)) *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call) Return(err error) *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNodeSecurityGroupUseCase creates a new instance of MockNodeSecurityGroupUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeSecurityGroupUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeSecurityGroupUseCase {
	mock := &MockNodeSecurityGroupUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeSecurityGroupUseCase is an autogenerated mock type for the NodeSecurityGroupUseCase type
type MockNodeSecurityGroupUseCase struct {
	mock.Mock
}

type MockNodeSecurityGroupUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeSecurityGroupUseCase) EXPECT() *MockNodeSecurityGroupUseCase_Expecter {
	return &MockNodeSecurityGroupUseCase_Expecter{mock: &_m.Mock}
}

// DeleteNodeSecurityGroupUseCase provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) DeleteNodeSecurityGroupUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNodeSecurityGroupUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNodeSecurityGroupUseCase'
type MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call struct {
	*mock.Call
}

// DeleteNodeSecurityGroupUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockNodeSecurityGroupUseCase_Expecter) DeleteNodeSecurityGroupUseCase(ctx interface{}, req interface{}) *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call {
	return &MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call{Call: _e.mock.On("DeleteNodeSecurityGroupUseCase", ctx, req)}
}

func (_c *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call) Return(err error) *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureNodeSecurityGroupUseCase provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) EnsureNodeSecurityGroupUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureNodeSecurityGroupUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureNodeSecurityGroupUseCase'
type MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call struct {
	*mock.Call
}

// EnsureNodeSecurityGroupUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockNodeSecurityGroupUseCase_Expecter) EnsureNodeSecurityGroupUseCase(ctx interface{}, req interface{}) *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call {
	return &MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call{Call: _e.mock.On("EnsureNodeSecurityGroupUseCase", ctx, req)}
}

func (_c *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call) Return(err error) *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitNodeSecurityGroupUseCase provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) InitNodeSecurityGroupUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitNodeSecurityGroupUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitNodeSecurityGroupUseCase'
type MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call struct {
	*mock.Call
}

// InitNodeSecurityGroupUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNodeSecurityGroupUseCase_Expecter) InitNodeSecurityGroupUseCase(ctx interface{}) *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call {
	return &MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call{Call: _e.mock.On("InitNodeSecurityGroupUseCase", ctx)}
}

func (_c *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call) Run(run func(ctx context.Context)) *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call) Return(err error) *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIngressUseCase creates a new instance of MockIngressUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngressUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngressUseCase {
	mock := &MockIngressUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIngressUseCase is an autogenerated mock type for the IngressUseCase type
type MockIngressUseCase struct {
	mock.Mock
}

type MockIngressUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngressUseCase) EXPECT() *MockIngressUseCase_Expecter {
	return &MockIngressUseCase_Expecter{mock: &_m.Mock}
}

// DeleteIngressUseCase provides a mock function for the type MockIngressUseCase
func (_mock *MockIngressUseCase) DeleteIngressUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIngressUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIngressUseCase_DeleteIngressUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIngressUseCase'
type MockIngressUseCase_DeleteIngressUseCase_Call struct {
	*mock.Call
}

// DeleteIngressUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockIngressUseCase_Expecter) DeleteIngressUseCase(ctx interface{}, req interface{}) *MockIngressUseCase_DeleteIngressUseCase_Call {
	return &MockIngressUseCase_DeleteIngressUseCase_Call{Call: _e.mock.On("DeleteIngressUseCase", ctx, req)}
}

func (_c *MockIngressUseCase_DeleteIngressUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockIngressUseCase_DeleteIngressUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIngressUseCase_DeleteIngressUseCase_Call) Return(err error) *MockIngressUseCase_DeleteIngressUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIngressUseCase_DeleteIngressUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockIngressUseCase_DeleteIngressUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureIngressUseCase provides a mock function for the type MockIngressUseCase
func (_mock *MockIngressUseCase) EnsureIngressUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureIngressUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIngressUseCase_EnsureIngressUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureIngressUseCase'
type MockIngressUseCase_EnsureIngressUseCase_Call struct {
	*mock.Call
}

// EnsureIngressUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockIngressUseCase_Expecter) EnsureIngressUseCase(ctx interface{}, req interface{}) *MockIngressUseCase_EnsureIngressUseCase_Call {
	return &MockIngressUseCase_EnsureIngressUseCase_Call{Call: _e.mock.On("EnsureIngressUseCase", ctx, req)}
}

func (_c *MockIngressUseCase_EnsureIngressUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockIngressUseCase_EnsureIngressUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIngressUseCase_EnsureIngressUseCase_Call) Return(err error) *MockIngressUseCase_EnsureIngressUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIngressUseCase_EnsureIngressUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockIngressUseCase_EnsureIngressUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitIngressUseCase provides a mock function for the type MockIngressUseCase
func (_mock *MockIngressUseCase) InitIngressUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitIngressUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIngressUseCase_InitIngressUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitIngressUseCase'
type MockIngressUseCase_InitIngressUseCase_Call struct {
	*mock.Call
}

// InitIngressUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIngressUseCase_Expecter) InitIngressUseCase(ctx interface{}) *MockIngressUseCase_InitIngressUseCase_Call {
	return &MockIngressUseCase_InitIngressUseCase_Call{Call: _e.mock.On("InitIngressUseCase", ctx)}
}

func (_c *MockIngressUseCase_InitIngressUseCase_Call) Run(run func(ctx context.Context)) *MockIngressUseCase_InitIngressUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIngressUseCase_InitIngressUseCase_Call) Return(err error) *MockIngressUseCase_InitIngressUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIngressUseCase_InitIngressUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockIngressUseCase_InitIngressUseCase_Call {
	_c.Call.Return(run)
	return _c
}
