apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vngcloud-load-balancer-controller.fullname" . }}-lbc-viewer-role
  labels:
  {{- include "vngcloud-load-balancer-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - vks.vngcloud.vn
  resources:
  - loadbalancerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vks.vngcloud.vn
  resources:
  - loadbalancerconfigs/status
  verbs:
  - get
