apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vngcloud-load-balancer-controller.fullname" . }}-mysecret
  labels:
  {{- include "vngcloud-load-balancer-controller.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    chartVersion: {{ .Chart.Version }}
    {{- toYaml .Values.mysecret | nindent 4 }}
type: Opaque