apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vngcloud-load-balancer-controller.fullname" . }}-mysecret
  labels:
  {{- include "vngcloud-load-balancer-controller.labels" . | nindent 4 }}
stringData:
  config.yaml: {{ required "mysecret.configYaml is required" .Values.mysecret.configYaml
    | quote }}
type: Opaque