apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vngcloud-load-balancer-controller.fullname" . }}-controller-manager
  labels:
  {{- include "vngcloud-load-balancer-controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}