kubernetesClusterDomain: cluster.local
manager:
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: vcr.vngcloud.vn/81-vks-public/vngcloud-load-balancer-controller
      tag: "v0.2.1" # release
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
mysecret:
  cluster:
    clusterID: ""
    clusterName: ""
  global:
    clientID: ""
    clientSecret: ""
    identityURL: https://iamapis.vngcloud.vn/accounts-api
    vserverURL: https://hcm-3.api.vngcloud.vn/vserver
