# govulncheck ./...
name: govulncheck
on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Scan for Vulnerabilities in Code
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: 1.22.5
          go-package: ./...
