name: CI Dev

on: push

env:
  VERSION: v0.0.1
  CHART_VERSION: 0.0.1
  REPO: vcr.vngcloud.vn/60108-annd2-ingress

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the vCR
        uses: docker/login-action@v3
        with:
          registry: vcr.vngcloud.vn
          username: ${{ secrets.VCR_USER }}
          password: ${{ secrets.VCR_PASSWORD }}
      
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ env.COMMIT_SHORT_SHA }}
          # platforms: linux/amd64
          # outputs: type=registry
          tags: |
            ghcr.io/vngcloud/vngcloud-load-balancer-controller:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-load-balancer-controller:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-load-balancer-controller:${{ env.VERSION }}
          # target: vngcloud-load-balancer-controller

      - name: Push charts
        env:
          CHANGED_CHARTS: "charts/vngcloud-load-balancer-controller"
        run: |
          echo "$CHANGED_CHARTS"
          echo ${{ github.workspace }}
          cd ${{ github.workspace }} && ./push_tgz.sh oci://${{ env.REPO }}/vks-helm-charts $CHANGED_CHARTS ${{ env.CHART_VERSION }}
