name: Release

# RELEASE="1.0.9" bash -c 'git tag $RELEASE && git push origin $RELEASE'

on:
  push:
    tags:
      - "*" # Triggers on version tags, e.g., 1.0.0

env:
  REPO_HCM: vcr.vngcloud.vn/81-vks-public
  REPO_HAN: vcr-han.vngcloud.vn/81-vks-public

jobs:
  build_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Log in to the GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the vCR HCM
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: vcr.vngcloud.vn
          username: ${{ secrets.VCR_USER_PRO }}
          password: ${{ secrets.VCR_PASSWORD_PRO }}

      - name: Log in to the vCR HAN
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: vcr-han.vngcloud.vn
          username: ${{ secrets.VCR_USER_HAN_PRO }}
          password: ${{ secrets.VCR_PASSWORD_HAN_PRO }}

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Debug
        run: echo ${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          context: .
          push: true
          build-args: |
            VERSION=v${{ github.ref_name }}
            COMMIT=${{ env.COMMIT_SHORT_SHA }}
          # platforms: linux/amd64
          # outputs: type=registry
          tags: |
            ghcr.io/vngcloud/vngcloud-load-balancer-controller:${{ env.COMMIT_SHORT_SHA }}
            ghcr.io/vngcloud/vngcloud-load-balancer-controller:v${{ github.ref_name }}
            ${{ env.REPO_HCM }}/vngcloud-load-balancer-controller:${{ env.COMMIT_SHORT_SHA }}
            ${{ env.REPO_HAN }}/vngcloud-load-balancer-controller:${{ env.COMMIT_SHORT_SHA }}
            ${{ env.REPO_HCM }}/vngcloud-load-balancer-controller:v${{ github.ref_name }}
            ${{ env.REPO_HAN }}/vngcloud-load-balancer-controller:v${{ github.ref_name }}
            ${{ env.REPO_HCM }}/vngcloud-load-balancer-controller:latest
            ${{ env.REPO_HAN }}/vngcloud-load-balancer-controller:latest
          # target: vngcloud-load-balancer-controller

      - name: Push charts
        env:
          CHANGED_CHARTS: "charts/vngcloud-load-balancer-controller"
        run: |
          helm package ./charts/vngcloud-load-balancer-controller --version ${{ github.ref_name }} --app-version v${{ github.ref_name }}
          helm push ./*.tgz oci://${{ env.REPO_HCM }}/vks-helm-charts
          helm push ./*.tgz oci://${{ env.REPO_HAN }}/vks-helm-charts

  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${{ github.ref_name }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${{ github.ref_name }}" \
              --generate-notes
